### PR TITLE
Adding patient risk endpoint

### PR DESCRIPTION
**Pull request by ml9951**

### CODE REVIEW

**Comment by klandell** [comment]
@ml9951 The endpoint is missing the birth category.  A mother falls into the birth category if they are postpartum for <= 3 days, she falls in the postpartum category only after the 3rd day.  You can use `dias_posparto + date_part('day', AGE(fecha_consulta)) as days_postpartum` to calculate the postpartum days.

**Comment by klandell** [comment]
@ml9951 Also, see below fir the columns that should be returned for pregnancy, birth, and postpartum.

pregnancy columns:
patient number, weeks pregnant, level of risk

(the following two have the same columns):
birth columns:
patient number, dias_postparto (postpartum days), level of risk

postpartum columns:
patient number, dias_postparto (postpartum days), level of risk

**Comment by klandell** [comment]
Additionally, please include the date the case was registered, for all categories.

**Comment by ml9951** [comment]
Just pushed a commit.  If it looks OK, go ahead and merge

**Comment by klandell** [comment]
I think it looks okay.  Can you just fix the days_postpartum calculation that I had added to the Fixtures endpoint?

**Comment by ml9951** [comment]
done

**Pull request merged**
